# Generated by Django 4.2.7 on 2023-11-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
