# Generated by Django 4.2.7 on 2023-11-18 21:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None),
        ),
        migrations.AlterField(
            model_name='poll',
            name='votes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=None),
        ),
    ]
