# Generated by Django 4.2.7 on 2023-11-19 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_poll_options_alter_poll_votes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='approved',
            new_name='is_approved',
        ),
    ]
